### ISSUE TITLE
2.1.2 创建控制器类 - Model键值错误

### ISSUE THREAD

**Issue by vansonliu** [LeonLi0102/spring-in-action-v6-translate#17]
![image](https://user-images.githubusercontent.com/15120993/150639254-4a1d0829-ca9d-45b6-9a7b-de67d7c80f60.png)

key应修改为design与template一致

`model.addAttribute("design", new Taco());`

**Comment by LeonLi0102** [comment]
感谢！
如果可能，欢迎提pr
